FROM node:18-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

#install dependencies
RUN npm install

RUN cd packages/db && npx prisma generate && cd ../..

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN npm run build

CMD [ "npm", "run", "start" ] 