name: Build on merge
on:
  push:
    branches:
      - main

jobs:
  Continuous-Integration:
    name: Performs Build on the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: USE Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Generate prisma client
        run: npx prisma generate

      - name: Run Build script
        run: npm run build
